server:
  port: 21888
eureka:
  client:
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true。
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka;多个地址可使用 , 分隔。